print()
print("Welcome to treasure island")
print()
a1 = input("Do you want to take a 'right' or 'left' ? ")
a1 = a1.lower()
if a1 == 'left':
    print()
    print("You reached a lake")
    print()
    a2 = input("Do you want to wait for a boat or swim ? ")
    a2 = a2.lower()
    if a2 == 'swim':
        print()
        print("You reached a house with 3 doors - ")
        print()
        print("1. RED   ")
        print("2. YELLOW")
        print("3. BLUE  ")
        print()
        a3 = input("Which door do you want to open ? ")
        a3 = a3.lower()
        if a3 == 'yellow' or a3 == '2':
            print()
            print("CONGRATULATIONS")
            print("You have found the treasure")
        elif a3 =='red' or a3 == '1':
            print()
            print("It was the red room... CHRIS EVANS found you...")
            print("YOU CAME")
            print()
            print("GAME OVER")
        else:
            print()
            print("There was a Lion behind that door... You died")
            print()
            print("GAME OVER")
    else:
        print()
        print("The Boat took too long... You froze to death")
        print("GAME OVER")
else:
    print()
    print("A hunter mistook you for a Dinosaur... You got shot")
    print("GAME OVER")